name: Build job

on:
  push:

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        configuration: [Release]
        include:
        - os: windows-latest
          OS_NAME: Windows x64
          DOTNET_RUNTIME_IDENTIFIER: win-x64
          RELEASE_ZIP_OS_NAME: win_x64

      fail-fast: false
    env:
      POWERSHELL_TELEMETRY_OPTOUT: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Ensure NuGet Source
        uses: fabriciomurta/ensure-nuget-source@v1
      - name: Clear
        run: dotnet clean && dotnet nuget locals all --clear
      - name: Build
        run: dotnet build -c "${{ matrix.configuration }}" 
      - name: Test
        run: dotnet test -c "${{ matrix.configuration }}"
      - name: Publish SoH Config
        run: dotnet publish -c "${{ matrix.configuration }}" -r "${{ matrix.DOTNET_RUNTIME_IDENTIFIER }}" -o ./publish --self-contained
      - name: Upload SoH Config artifact
        uses: actions/upload-artifact@v3
        with:
          path: publish
